version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.7.1
    steps:
      - checkout
      - run: ls -la
      - run: ( find . -type d -name ".git" && find . -name ".gitignore" && find . -name ".gitmodules" ) | xargs rm -v -rf
      - run: ls -la
